homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
#TODO: rename to base_test
basic_test:
    path: /test/{testName}/{testUrlId}/{previous}
    defaults: { _controller: AppBundle:Test:basic, testUrlId: '', previous: '' }
